services:
  nginx:
    init: true
    build: requirements/nginx/
    #build:
    #  context: .
    #  dockerfile: requirements/nginx/Dockerfile
    container_name: j_nginx
    depends_on:
      #- wordpress
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/
    restart: always
    networks:
      - inception

  wordpress:
    init: true
    build:
      context: requirements/wordpress/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: j_wordpress
    depends_on:
      #- mariadb
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    restart: always
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    init: true
    env_file:
      - .env
    build: 
      context: requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: j_mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db-volume:/var/lib/mysql/
    networks:
      - inception

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      #Docker를 사용하는 호스트 시스템의 `/home/login/data` 폴더에서 `volume`을 사용할 수 있습니다.
      #device: /home/${USER}/data/wordpress
      device: ../data/wordpress
  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: ../data/mariadb

networks: 
  inception:
    driver: bridge
