services:
  nginx:
    init: true
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/
    restart: always
    networks:
      - inception

  wordpress:
    init: true
    build:
      context: requirements/wordpress/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    restart: always
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    init: true
    env_file:
      - .env
    build: 
      context: requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db-volume:/var/lib/mysql/
    networks:
      - inception
    
  redis:
    init: true
    build: requirements/bonus/redis/
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inception

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/seunghye/data/wordpress
  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/seunghye/data/mariadb

networks: 
  inception:
    driver: bridge
