services:
  nginx:
    init: true
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/
    restart: always
    networks:
      - inception

  wordpress:
    init: true
    build:
      context: requirements/wordpress/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        REDIS_HOST : ${REDIS_HOST}
        REDIS_DATABASE : ${REDIS_DATABASE}
        REDIS_MAXTTL : ${REDIS_MAXTTL}
        REDIS_TIMEOUT : ${REDIS_TIMEOUT}
        REDIS_READ_TIMEOUT : ${REDIS_READ_TIMEOUT}
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    restart: always
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    init: true
    env_file:
      - .env
    build: 
      context: requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db-volume:/var/lib/mysql/
      - log-volume:/var/log/mysql/
    networks:
      - inception
    
  redis:
    init: true
    build: requirements/bonus/redis/
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inception

  vsftpd:
    init: true
    build:
      context: requirements/bonus/vsftpd/
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    container_name: vsftpd
    restart: always
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/
    networks:
     - inception

  adminer:
    init: true
    build: requirements/bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - wp-volume:/var/www/
    networks:
     - inception
  
  site:
    init: true
    build: requirements/bonus/site
    container_name: site
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "4242:4242"
    networks:
     - inception

  logrotate:
    init: true
    build: requirements/bonus/logrotate
    container_name: logrotate
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - log-volume:/var/log/mysql/
    networks:
     - inception

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/seunghye/data/wordpress
  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/seunghye/data/mariadb
  log-volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/seunghye/data/mariadb_log
    

networks: 
  inception:
    driver: bridge
    name: inception
